package com.jhua.model;

import java.util.Date;

public class ZammerGames {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.id
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.zammer_game_id
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private Integer zammerGameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.api_version
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private Integer apiVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.res_msg
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private String resMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.content_name
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private String contentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.download_url
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private String downloadUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.img_url
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.update_time
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.create_time
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.id
     *
     * @return the value of zammer_games.id
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.id
     *
     * @param id the value for zammer_games.id
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.zammer_game_id
     *
     * @return the value of zammer_games.zammer_game_id
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public Integer getZammerGameId() {
        return zammerGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.zammer_game_id
     *
     * @param zammerGameId the value for zammer_games.zammer_game_id
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setZammerGameId(Integer zammerGameId) {
        this.zammerGameId = zammerGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.api_version
     *
     * @return the value of zammer_games.api_version
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public Integer getApiVersion() {
        return apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.api_version
     *
     * @param apiVersion the value for zammer_games.api_version
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setApiVersion(Integer apiVersion) {
        this.apiVersion = apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.res_msg
     *
     * @return the value of zammer_games.res_msg
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public String getResMsg() {
        return resMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.res_msg
     *
     * @param resMsg the value for zammer_games.res_msg
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setResMsg(String resMsg) {
        this.resMsg = resMsg == null ? null : resMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.content_name
     *
     * @return the value of zammer_games.content_name
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public String getContentName() {
        return contentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.content_name
     *
     * @param contentName the value for zammer_games.content_name
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setContentName(String contentName) {
        this.contentName = contentName == null ? null : contentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.download_url
     *
     * @return the value of zammer_games.download_url
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.download_url
     *
     * @param downloadUrl the value for zammer_games.download_url
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.img_url
     *
     * @return the value of zammer_games.img_url
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.img_url
     *
     * @param imgUrl the value for zammer_games.img_url
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.update_time
     *
     * @return the value of zammer_games.update_time
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.update_time
     *
     * @param updateTime the value for zammer_games.update_time
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.create_time
     *
     * @return the value of zammer_games.create_time
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.create_time
     *
     * @param createTime the value for zammer_games.create_time
     *
     * @mbg.generated Mon Aug 16 11:25:00 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}