package com.jhua.dao;

import com.jhua.model.GamesImages;
import com.jhua.model.GamesImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GamesImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    long countByExample(GamesImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int deleteByExample(GamesImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int insert(GamesImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int insertSelective(GamesImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    List<GamesImages> selectByExample(GamesImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    GamesImages selectByPrimaryKey(Integer id);
    GamesImages selectByGameId(Integer game_id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") GamesImages record, @Param("example") GamesImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int updateByExample(@Param("record") GamesImages record, @Param("example") GamesImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int updateByPrimaryKeySelective(GamesImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    int updateByPrimaryKey(GamesImages record);
}