package com.jhua.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GamesImagesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public GamesImagesExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNull() {
            addCriterion("game_id is null");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNotNull() {
            addCriterion("game_id is not null");
            return (Criteria) this;
        }

        public Criteria andGameIdEqualTo(Integer value) {
            addCriterion("game_id =", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotEqualTo(Integer value) {
            addCriterion("game_id <>", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThan(Integer value) {
            addCriterion("game_id >", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_id >=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThan(Integer value) {
            addCriterion("game_id <", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThanOrEqualTo(Integer value) {
            addCriterion("game_id <=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdIn(List<Integer> values) {
            addCriterion("game_id in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotIn(List<Integer> values) {
            addCriterion("game_id not in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdBetween(Integer value1, Integer value2) {
            addCriterion("game_id between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotBetween(Integer value1, Integer value2) {
            addCriterion("game_id not between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andSourceListIsNull() {
            addCriterion("source_list is null");
            return (Criteria) this;
        }

        public Criteria andSourceListIsNotNull() {
            addCriterion("source_list is not null");
            return (Criteria) this;
        }

        public Criteria andSourceListEqualTo(String value) {
            addCriterion("source_list =", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListNotEqualTo(String value) {
            addCriterion("source_list <>", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListGreaterThan(String value) {
            addCriterion("source_list >", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListGreaterThanOrEqualTo(String value) {
            addCriterion("source_list >=", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListLessThan(String value) {
            addCriterion("source_list <", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListLessThanOrEqualTo(String value) {
            addCriterion("source_list <=", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListLike(String value) {
            addCriterion("source_list like", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListNotLike(String value) {
            addCriterion("source_list not like", value, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListIn(List<String> values) {
            addCriterion("source_list in", values, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListNotIn(List<String> values) {
            addCriterion("source_list not in", values, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListBetween(String value1, String value2) {
            addCriterion("source_list between", value1, value2, "sourceList");
            return (Criteria) this;
        }

        public Criteria andSourceListNotBetween(String value1, String value2) {
            addCriterion("source_list not between", value1, value2, "sourceList");
            return (Criteria) this;
        }

        public Criteria andUrlVideoIsNull() {
            addCriterion("url_video is null");
            return (Criteria) this;
        }

        public Criteria andUrlVideoIsNotNull() {
            addCriterion("url_video is not null");
            return (Criteria) this;
        }

        public Criteria andUrlVideoEqualTo(String value) {
            addCriterion("url_video =", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoNotEqualTo(String value) {
            addCriterion("url_video <>", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoGreaterThan(String value) {
            addCriterion("url_video >", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoGreaterThanOrEqualTo(String value) {
            addCriterion("url_video >=", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoLessThan(String value) {
            addCriterion("url_video <", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoLessThanOrEqualTo(String value) {
            addCriterion("url_video <=", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoLike(String value) {
            addCriterion("url_video like", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoNotLike(String value) {
            addCriterion("url_video not like", value, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoIn(List<String> values) {
            addCriterion("url_video in", values, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoNotIn(List<String> values) {
            addCriterion("url_video not in", values, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoBetween(String value1, String value2) {
            addCriterion("url_video between", value1, value2, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlVideoNotBetween(String value1, String value2) {
            addCriterion("url_video not between", value1, value2, "urlVideo");
            return (Criteria) this;
        }

        public Criteria andUrlImgIsNull() {
            addCriterion("url_img is null");
            return (Criteria) this;
        }

        public Criteria andUrlImgIsNotNull() {
            addCriterion("url_img is not null");
            return (Criteria) this;
        }

        public Criteria andUrlImgEqualTo(String value) {
            addCriterion("url_img =", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgNotEqualTo(String value) {
            addCriterion("url_img <>", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgGreaterThan(String value) {
            addCriterion("url_img >", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgGreaterThanOrEqualTo(String value) {
            addCriterion("url_img >=", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgLessThan(String value) {
            addCriterion("url_img <", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgLessThanOrEqualTo(String value) {
            addCriterion("url_img <=", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgLike(String value) {
            addCriterion("url_img like", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgNotLike(String value) {
            addCriterion("url_img not like", value, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgIn(List<String> values) {
            addCriterion("url_img in", values, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgNotIn(List<String> values) {
            addCriterion("url_img not in", values, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgBetween(String value1, String value2) {
            addCriterion("url_img between", value1, value2, "urlImg");
            return (Criteria) this;
        }

        public Criteria andUrlImgNotBetween(String value1, String value2) {
            addCriterion("url_img not between", value1, value2, "urlImg");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table games_images
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 19 17:14:26 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table games_images
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}