package com.jhua.model;

import java.util.Date;

public class GamesImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.id
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.game_id
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private Integer gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.source_list
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private String sourceList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.url_video
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private String urlVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.url_img
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private String urlImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.name
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.type
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.update_time
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games_images.create_time
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.id
     *
     * @return the value of games_images.id
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.id
     *
     * @param id the value for games_images.id
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.game_id
     *
     * @return the value of games_images.game_id
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.game_id
     *
     * @param gameId the value for games_images.game_id
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.source_list
     *
     * @return the value of games_images.source_list
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public String getSourceList() {
        return sourceList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.source_list
     *
     * @param sourceList the value for games_images.source_list
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setSourceList(String sourceList) {
        this.sourceList = sourceList == null ? null : sourceList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.url_video
     *
     * @return the value of games_images.url_video
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public String getUrlVideo() {
        return urlVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.url_video
     *
     * @param urlVideo the value for games_images.url_video
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setUrlVideo(String urlVideo) {
        this.urlVideo = urlVideo == null ? null : urlVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.url_img
     *
     * @return the value of games_images.url_img
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public String getUrlImg() {
        return urlImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.url_img
     *
     * @param urlImg the value for games_images.url_img
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setUrlImg(String urlImg) {
        this.urlImg = urlImg == null ? null : urlImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.name
     *
     * @return the value of games_images.name
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.name
     *
     * @param name the value for games_images.name
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.type
     *
     * @return the value of games_images.type
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.type
     *
     * @param type the value for games_images.type
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.update_time
     *
     * @return the value of games_images.update_time
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.update_time
     *
     * @param updateTime the value for games_images.update_time
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games_images.create_time
     *
     * @return the value of games_images.create_time
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games_images.create_time
     *
     * @param createTime the value for games_images.create_time
     *
     * @mbg.generated Thu Aug 19 17:14:26 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}