package com.jhua.model;

import java.util.Date;

public class ZammerGames {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.zammer_game_id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private Integer zammerGameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.content_name
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String contentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.api_version
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private Integer apiVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.summary
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.version_name
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String versionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.res_code
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String resCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.res_msg
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String resMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.img_url
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.download_url
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String downloadUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.exe_files
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String exeFiles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.file_num
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private Integer fileNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.tag_ids
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String tagIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.tag_names
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String tagNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.task_id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.md5
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.online
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private Integer online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.create_time
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.update_time
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zammer_games.file_length
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    private String fileLength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.id
     *
     * @return the value of zammer_games.id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.id
     *
     * @param id the value for zammer_games.id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.zammer_game_id
     *
     * @return the value of zammer_games.zammer_game_id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public Integer getZammerGameId() {
        return zammerGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.zammer_game_id
     *
     * @param zammerGameId the value for zammer_games.zammer_game_id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setZammerGameId(Integer zammerGameId) {
        this.zammerGameId = zammerGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.content_name
     *
     * @return the value of zammer_games.content_name
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getContentName() {
        return contentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.content_name
     *
     * @param contentName the value for zammer_games.content_name
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setContentName(String contentName) {
        this.contentName = contentName == null ? null : contentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.api_version
     *
     * @return the value of zammer_games.api_version
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public Integer getApiVersion() {
        return apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.api_version
     *
     * @param apiVersion the value for zammer_games.api_version
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setApiVersion(Integer apiVersion) {
        this.apiVersion = apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.summary
     *
     * @return the value of zammer_games.summary
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.summary
     *
     * @param summary the value for zammer_games.summary
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.version_name
     *
     * @return the value of zammer_games.version_name
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.version_name
     *
     * @param versionName the value for zammer_games.version_name
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.res_code
     *
     * @return the value of zammer_games.res_code
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.res_code
     *
     * @param resCode the value for zammer_games.res_code
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setResCode(String resCode) {
        this.resCode = resCode == null ? null : resCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.res_msg
     *
     * @return the value of zammer_games.res_msg
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getResMsg() {
        return resMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.res_msg
     *
     * @param resMsg the value for zammer_games.res_msg
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setResMsg(String resMsg) {
        this.resMsg = resMsg == null ? null : resMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.img_url
     *
     * @return the value of zammer_games.img_url
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.img_url
     *
     * @param imgUrl the value for zammer_games.img_url
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.download_url
     *
     * @return the value of zammer_games.download_url
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.download_url
     *
     * @param downloadUrl the value for zammer_games.download_url
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.exe_files
     *
     * @return the value of zammer_games.exe_files
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getExeFiles() {
        return exeFiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.exe_files
     *
     * @param exeFiles the value for zammer_games.exe_files
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setExeFiles(String exeFiles) {
        this.exeFiles = exeFiles == null ? null : exeFiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.file_num
     *
     * @return the value of zammer_games.file_num
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public Integer getFileNum() {
        return fileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.file_num
     *
     * @param fileNum the value for zammer_games.file_num
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setFileNum(Integer fileNum) {
        this.fileNum = fileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.tag_ids
     *
     * @return the value of zammer_games.tag_ids
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getTagIds() {
        return tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.tag_ids
     *
     * @param tagIds the value for zammer_games.tag_ids
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds == null ? null : tagIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.tag_names
     *
     * @return the value of zammer_games.tag_names
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getTagNames() {
        return tagNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.tag_names
     *
     * @param tagNames the value for zammer_games.tag_names
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setTagNames(String tagNames) {
        this.tagNames = tagNames == null ? null : tagNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.task_id
     *
     * @return the value of zammer_games.task_id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.task_id
     *
     * @param taskId the value for zammer_games.task_id
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.md5
     *
     * @return the value of zammer_games.md5
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.md5
     *
     * @param md5 the value for zammer_games.md5
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.online
     *
     * @return the value of zammer_games.online
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.online
     *
     * @param online the value for zammer_games.online
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setOnline(Integer online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.create_time
     *
     * @return the value of zammer_games.create_time
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.create_time
     *
     * @param createTime the value for zammer_games.create_time
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.update_time
     *
     * @return the value of zammer_games.update_time
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.update_time
     *
     * @param updateTime the value for zammer_games.update_time
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zammer_games.file_length
     *
     * @return the value of zammer_games.file_length
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public String getFileLength() {
        return fileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zammer_games.file_length
     *
     * @param fileLength the value for zammer_games.file_length
     *
     * @mbg.generated Wed Sep 01 15:28:22 CST 2021
     */
    public void setFileLength(String fileLength) {
        this.fileLength = fileLength == null ? null : fileLength.trim();
    }
}